version: '3'
services:
  supportbot:
    # build: .
    image: "bostrot/telegram-support-bot:latest"
    restart: unless-stopped
    volumes:
      - ${PWD}/config:/telegram-support-bot/config
    ports:
      - "8080:8080"
